//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biometric_characteristics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fingerprint
    {
        public int Id { get; set; }
        public string Hand { get; set; }
        public string Finger { get; set; }
    
        public virtual Sample Sample { get; set; }
    }
}
