//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biometric_characteristics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keystroke
    {
        public int Id { get; set; }
        public bool Success { get; set; }
        public string Password { get; set; }
        public string PpTime { get; set; }
        public string RrTime { get; set; }
        public string PrTime { get; set; }
        public string RpTime { get; set; }
        public string Vector { get; set; }
        public string TimeToType { get; set; }
        public string RawPress { get; set; }
        public string RawRelease { get; set; }
        public int PersonId { get; set; }
        public Nullable<int> KeystrokeDatasetId { get; set; }
        public Nullable<int> KeyboardId { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual KeystrokeDataset KeystrokeDataset { get; set; }
        public virtual Keyboard Keyboard { get; set; }
    }
}
