//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biometric_characteristics.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person> PersonSet { get; set; }
        public virtual DbSet<Device> DeviceSet { get; set; }
        public virtual DbSet<Sample> SampleSet { get; set; }
        public virtual DbSet<Keystroke> KeystrokeSet { get; set; }
        public virtual DbSet<Keyboard> KeyboardSet { get; set; }
        public virtual DbSet<Signature> SignatureSet { get; set; }
        public virtual DbSet<Fingerprint> FingerprintSet { get; set; }
        public virtual DbSet<Palmprint> PalmprintSet { get; set; }
        public virtual DbSet<Face> FaceSet { get; set; }
        public virtual DbSet<Speech> SpeechSet { get; set; }
        public virtual DbSet<Iris> IrisSet { get; set; }
        public virtual DbSet<Handwriting> HandwritingSet { get; set; }
        public virtual DbSet<Text> TextSet { get; set; }
        public virtual DbSet<Language> LanguageSet { get; set; }
        public virtual DbSet<Gait> GaitSet { get; set; }
        public virtual DbSet<DeviceType> DeviceTypeSet { get; set; }
        public virtual DbSet<SampleType> SampleTypeSet { get; set; }
        public virtual DbSet<SampleDataset> SampleDatasetSet { get; set; }
        public virtual DbSet<KeystrokeDataset> KeystrokeDatasetSet { get; set; }
    }
}
