//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biometric_characteristics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sample
    {
        public int Id { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public string DateCreated { get; set; }
        public int PersonId { get; set; }
        public int SampleTypeId { get; set; }
        public Nullable<int> DeviceId { get; set; }
        public Nullable<int> SampleDatasetId { get; set; }
        public string FullFilePath { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual SampleType SampleType { get; set; }
        public virtual Device Device { get; set; }
        public virtual Fingerprint Fingerprint { get; set; }
        public virtual Palmprint Palmprint { get; set; }
        public virtual Face Face { get; set; }
        public virtual Iris Iris { get; set; }
        public virtual Gait Gait { get; set; }
        public virtual Speech Speech { get; set; }
        public virtual Handwriting Handwriting { get; set; }
        public virtual Signature Signature { get; set; }
        public virtual SampleDataset SampleDataset { get; set; }
    }
}
