/*
  This file is automatically generated. Any changes will be overwritten.
  Modify app.module.ts instead.
*/
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { RadzenModule } from '@radzen/angular';

import { AppRoutes } from './app.routes';
import { AppComponent, PageTitleComponent } from './app.component';
export { AppComponent } from './app.component';
import { DeviceComponent } from './device/device.component';
import { AddDeviceSetComponent } from './add-device-set/add-device-set.component';
import { EditDeviceSetComponent } from './edit-device-set/edit-device-set.component';
import { DeviceTypeComponent } from './device-type/device-type.component';
import { AddDeviceTypeSetComponent } from './add-device-type-set/add-device-type-set.component';
import { EditDeviceTypeSetComponent } from './edit-device-type-set/edit-device-type-set.component';
import { FaceComponent } from './face/face.component';
import { AddFaceSetComponent } from './add-face-set/add-face-set.component';
import { EditFaceSetComponent } from './edit-face-set/edit-face-set.component';
import { FingerprintComponent } from './fingerprint/fingerprint.component';
import { AddFingerprintSetComponent } from './add-fingerprint-set/add-fingerprint-set.component';
import { EditFingerprintSetComponent } from './edit-fingerprint-set/edit-fingerprint-set.component';
import { GaitComponent } from './gait/gait.component';
import { AddGaitSetComponent } from './add-gait-set/add-gait-set.component';
import { EditGaitSetComponent } from './edit-gait-set/edit-gait-set.component';
import { HandwritingComponent } from './handwriting/handwriting.component';
import { AddHandwritingSetComponent } from './add-handwriting-set/add-handwriting-set.component';
import { EditHandwritingSetComponent } from './edit-handwriting-set/edit-handwriting-set.component';
import { IrisComponent } from './iris/iris.component';
import { AddIrisSetComponent } from './add-iris-set/add-iris-set.component';
import { EditIrisSetComponent } from './edit-iris-set/edit-iris-set.component';
import { KeyboardComponent } from './keyboard/keyboard.component';
import { AddKeyboardSetComponent } from './add-keyboard-set/add-keyboard-set.component';
import { EditKeyboardSetComponent } from './edit-keyboard-set/edit-keyboard-set.component';
import { KeystrokeDatasetComponent } from './keystroke-dataset/keystroke-dataset.component';
import { AddKeystrokeDatasetSetComponent } from './add-keystroke-dataset-set/add-keystroke-dataset-set.component';
import { EditKeystrokeDatasetSetComponent } from './edit-keystroke-dataset-set/edit-keystroke-dataset-set.component';
import { KeystrokeComponent } from './keystroke/keystroke.component';
import { AddKeystrokeSetComponent } from './add-keystroke-set/add-keystroke-set.component';
import { EditKeystrokeSetComponent } from './edit-keystroke-set/edit-keystroke-set.component';
import { LanguageComponent } from './language/language.component';
import { AddLanguageSetComponent } from './add-language-set/add-language-set.component';
import { EditLanguageSetComponent } from './edit-language-set/edit-language-set.component';
import { PalmprintComponent } from './palmprint/palmprint.component';
import { AddPalmprintSetComponent } from './add-palmprint-set/add-palmprint-set.component';
import { EditPalmprintSetComponent } from './edit-palmprint-set/edit-palmprint-set.component';
import { PersonComponent } from './person/person.component';
import { AddPersonSetComponent } from './add-person-set/add-person-set.component';
import { EditPersonSetComponent } from './edit-person-set/edit-person-set.component';
import { SampleDatasetComponent } from './sample-dataset/sample-dataset.component';
import { AddSampleDatasetSetComponent } from './add-sample-dataset-set/add-sample-dataset-set.component';
import { EditSampleDatasetSetComponent } from './edit-sample-dataset-set/edit-sample-dataset-set.component';
import { SampleComponent } from './sample/sample.component';
import { AddSampleSetComponent } from './add-sample-set/add-sample-set.component';
import { EditSampleSetComponent } from './edit-sample-set/edit-sample-set.component';
import { SampleTypeComponent } from './sample-type/sample-type.component';
import { AddSampleTypeSetComponent } from './add-sample-type-set/add-sample-type-set.component';
import { EditSampleTypeSetComponent } from './edit-sample-type-set/edit-sample-type-set.component';
import { SignatureComponent } from './signature/signature.component';
import { AddSignatureSetComponent } from './add-signature-set/add-signature-set.component';
import { EditSignatureSetComponent } from './edit-signature-set/edit-signature-set.component';
import { SpeechComponent } from './speech/speech.component';
import { AddSpeechSetComponent } from './add-speech-set/add-speech-set.component';
import { EditSpeechSetComponent } from './edit-speech-set/edit-speech-set.component';
import { TextComponent } from './text/text.component';
import { AddTextSetComponent } from './add-text-set/add-text-set.component';
import { EditTextSetComponent } from './edit-text-set/edit-text-set.component';

import { BiometricCharacteristicsModelService } from './biometric-characteristics-model.service';

export const AppDeclarations = [
  DeviceComponent,
  AddDeviceSetComponent,
  EditDeviceSetComponent,
  DeviceTypeComponent,
  AddDeviceTypeSetComponent,
  EditDeviceTypeSetComponent,
  FaceComponent,
  AddFaceSetComponent,
  EditFaceSetComponent,
  FingerprintComponent,
  AddFingerprintSetComponent,
  EditFingerprintSetComponent,
  GaitComponent,
  AddGaitSetComponent,
  EditGaitSetComponent,
  HandwritingComponent,
  AddHandwritingSetComponent,
  EditHandwritingSetComponent,
  IrisComponent,
  AddIrisSetComponent,
  EditIrisSetComponent,
  KeyboardComponent,
  AddKeyboardSetComponent,
  EditKeyboardSetComponent,
  KeystrokeDatasetComponent,
  AddKeystrokeDatasetSetComponent,
  EditKeystrokeDatasetSetComponent,
  KeystrokeComponent,
  AddKeystrokeSetComponent,
  EditKeystrokeSetComponent,
  LanguageComponent,
  AddLanguageSetComponent,
  EditLanguageSetComponent,
  PalmprintComponent,
  AddPalmprintSetComponent,
  EditPalmprintSetComponent,
  PersonComponent,
  AddPersonSetComponent,
  EditPersonSetComponent,
  SampleDatasetComponent,
  AddSampleDatasetSetComponent,
  EditSampleDatasetSetComponent,
  SampleComponent,
  AddSampleSetComponent,
  EditSampleSetComponent,
  SampleTypeComponent,
  AddSampleTypeSetComponent,
  EditSampleTypeSetComponent,
  SignatureComponent,
  AddSignatureSetComponent,
  EditSignatureSetComponent,
  SpeechComponent,
  AddSpeechSetComponent,
  EditSpeechSetComponent,
  TextComponent,
  AddTextSetComponent,
  EditTextSetComponent,
  AppComponent,
  PageTitleComponent
];

export const AppProviders = [
  BiometricCharacteristicsModelService,
];

export const AppImports = [
  BrowserModule,
  BrowserAnimationsModule,
  FormsModule,
  HttpModule,
  RadzenModule,
  AppRoutes
];
